# Generated by Django 5.1.3 on 2025-04-20 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha de la tarea')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora de la tarea')),
                ('visibilidad', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaClonada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clonacion', models.DateTimeField(auto_now_add=True)),
                ('modificada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_clonadas', to=settings.AUTH_USER_MODEL)),
                ('tarea_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='Organiza2.tarea')),
            ],
        ),
    ]
