services:
  - type: web
    name: Organiza2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      gunicorn proyectoTFG.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: proyectoTFG.settings
      - key: SECRET_KEY
        generateValue: true
